apiVersion: v1
kind: Pod
metadata:
  generateName: kueue-sleep-
  labels:
  namespace: kueue-managed-test
spec:
  containers:
    - name: sleep
      image: busybox
      command:
        - sleep
      args:
        - 3s
      resources:
        requests:
          cpu: 3
  restartPolicy: OnFailure
